<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useModifierStore } from '@/stores/modifier'
import type { ModifierGroup, ModifierOption } from '@/services/mockErpApi'
import { ArrowLeft, Save, X, Plus, Trash2, GripVertical } from '@lucide/vue'
import { useToast } from '@/composables/useToast'

const route = useRoute()
const router = useRouter()
const modifierStore = useModifierStore()
const { showToast } = useToast()

const isEditing = ref(false)
const isLoading = ref(true)
const isSaving = ref(false)

const formData = ref<Partial<ModifierGroup>>({
  name: '',
  description: '',
  status: 'Active',
  minSelections: 0,
  maxSelections: 1,
  options: []
})

onMounted(async () => {
  const id = route.params.id as string
  if (id) {
    isEditing.value = true
    if (modifierStore.modifierGroups.length === 0) {
      await modifierStore.fetchModifierGroups()
    }
    const group = modifierStore.getModifierGroupById(id)
    if (group) {
      // Deep copy to prevent store mutation
      formData.value = JSON.parse(JSON.stringify(group))
    } else {
      showToast('Error', 'Modifier Group not found', 'error')
      router.push('/catalog/modifiers')
      return
    }
  } else {
    // Add one empty option by default for new groups
    addOption()
  }
  isLoading.value = false
})

const addOption = () => {
  formData.value.options!.push({
    id: '', // Will be generated by API if empty
    name: '',
    priceAdjustment: 0,
    status: 'Active'
  })
}

const removeOption = (index: number) => {
  formData.value.options!.splice(index, 1)
}

const handleSave = async () => {
  // Validate Group Fields
  if (!formData.value.name || formData.value.name.trim() === '') {
    showToast('Validation Error', 'Modifier Group Name is required.', 'error')
    return
  }

  const minSel = Number(formData.value.minSelections)
  const maxSel = Number(formData.value.maxSelections)

  if (minSel < 0) {
    showToast('Validation Error', 'Minimum selections cannot be negative.', 'error')
    return
  }
  if (maxSel < 1) {
    showToast('Validation Error', 'Maximum selections must be at least 1.', 'error')
    return
  }
  if (minSel > maxSel) {
    showToast('Validation Error', 'Minimum selections cannot be greater than maximum selections.', 'error')
    return
  }

  // Validate Options
  if (!formData.value.options || formData.value.options.length < maxSel) {
    showToast('Validation Error', `You must provide at least ${maxSel} options to satisfy the maximum selections rule.`, 'error')
    return
  }

  const optionNames = new Set()
  for (const opt of formData.value.options) {
    if (!opt.name || opt.name.trim() === '') {
      showToast('Validation Error', 'All options must have a name.', 'error')
      return
    }
    const nameLower = opt.name.trim().toLowerCase()
    if (optionNames.has(nameLower)) {
      showToast('Validation Error', `Duplicate option name found: "${opt.name}". Options must be unique within a group.`, 'error')
      return
    }
    optionNames.add(nameLower)
  }

  isSaving.value = true
  try {
    const payload = {
      ...formData.value,
      minSelections: minSel,
      maxSelections: maxSel
    }

    if (isEditing.value) {
      await modifierStore.updateModifierGroup(formData.value.id!, payload as any)
      showToast('Success', 'Modifier group updated successfully.', 'success')
    } else {
      await modifierStore.createModifierGroup(payload as any)
      showToast('Success', 'Modifier group created successfully.', 'success')
    }
    router.push('/catalog/modifiers')
  } catch (e: any) {
    showToast('Error', e.message || 'Failed to save modifier group.', 'error')
  } finally {
    isSaving.value = false
  }
}

const handleCancel = () => {
  router.push('/catalog/modifiers')
}
</script>

<template>
  <div class="space-y-6 pb-12 max-w-5xl mx-auto">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div class="flex items-center space-x-3">
        <button 
          @click="handleCancel"
          class="p-2 text-gray-500 hover:text-gray-700 bg-white border border-gray-200 rounded-lg shadow-sm hover:bg-gray-50 transition-colors"
        >
          <ArrowLeft class="w-5 h-5" />
        </button>
        <div>
          <h1 class="text-2xl font-semibold text-gray-900 tracking-tight">
            {{ isEditing ? 'Edit Modifier Group' : 'New Modifier Group' }}
          </h1>
          <p class="mt-1 text-sm text-gray-500">
            {{ isEditing ? formData.name : 'Create a new group of modifiers (e.g. Sugar Level, Add-ons).' }}
          </p>
        </div>
      </div>
      
      <div class="flex items-center space-x-3">
        <button 
          @click="handleCancel"
          type="button" 
          :disabled="isSaving"
          class="flex items-center text-gray-900 bg-white border border-gray-200 focus:outline-none hover:bg-gray-50 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 shadow-sm disabled:opacity-50"
        >
          <X class="w-4 h-4 mr-2" />
          Cancel
        </button>
        <button 
          @click="handleSave"
          type="button" 
          :disabled="isSaving"
          class="flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 shadow-sm disabled:opacity-50"
        >
          <Save class="w-4 h-4 mr-2" />
          {{ isSaving ? 'Saving...' : 'Save Modifier Group' }}
        </button>
      </div>
    </div>

    <div v-if="isLoading" class="p-8 text-center text-gray-500 bg-white rounded-xl shadow-sm border border-gray-200">
      Loading...
    </div>
    
    <div v-else class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Left Column: General & Rules -->
      <div class="lg:col-span-1 space-y-6">
        
        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
          <div class="px-5 py-4 border-b border-gray-200 bg-gray-50/50">
            <h3 class="text-lg font-semibold text-gray-900">General Info</h3>
          </div>
          <div class="p-5 space-y-5">
            <div>
              <label class="block mb-2 text-sm font-medium text-gray-900">Group Name <span class="text-red-600">*</span></label>
              <input 
                type="text" 
                v-model="formData.name"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" 
                placeholder="e.g. Sugar Level" 
                required
              >
            </div>
            <div>
              <label class="block mb-2 text-sm font-medium text-gray-900">Description</label>
              <textarea 
                rows="2" 
                v-model="formData.description"
                class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500" 
                placeholder="Optional description..."
              ></textarea>
            </div>
            <div>
              <label class="block mb-2 text-sm font-medium text-gray-900">Status</label>
              <select 
                v-model="formData.status"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
              >
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
              </select>
            </div>
          </div>
        </div>

        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
          <div class="px-5 py-4 border-b border-gray-200 bg-gray-50/50">
            <h3 class="text-lg font-semibold text-gray-900">Selection Rules</h3>
            <p class="text-xs text-gray-500 mt-1">Define how many options the customer can select.</p>
          </div>
          <div class="p-5 space-y-5">
            <div>
              <label class="block mb-2 text-sm font-medium text-gray-900">Min Selections <span class="text-red-600">*</span></label>
              <input 
                type="number" 
                min="0"
                v-model="formData.minSelections"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" 
                required
              >
              <p class="text-xs text-gray-500 mt-1">Set to 0 to make this modifier group optional.</p>
            </div>
            <div>
              <label class="block mb-2 text-sm font-medium text-gray-900">Max Selections <span class="text-red-600">*</span></label>
              <input 
                type="number" 
                min="1"
                v-model="formData.maxSelections"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" 
                required
              >
              <p class="text-xs text-gray-500 mt-1">Set to 1 for single-choice (radio), or &gt;1 for multi-choice (checkbox).</p>
            </div>
            
            <div v-if="formData.minSelections! > 0" class="p-3 bg-red-50 text-red-700 text-sm rounded-lg border border-red-100 flex items-start gap-2">
              <span class="font-bold shrink-0">Note:</span>
              <span>Because Min Selections is greater than 0, customers <b>must</b> make a selection before adding to cart.</span>
            </div>
          </div>
        </div>

      </div>

      <!-- Right Column: Options List -->
      <div class="lg:col-span-2 space-y-6">
        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden flex flex-col h-full">
          <div class="px-5 py-4 border-b border-gray-200 bg-gray-50/50 flex justify-between items-center shrink-0">
            <div>
              <h3 class="text-lg font-semibold text-gray-900">Modifier Options</h3>
              <p class="text-xs text-gray-500 mt-1">Add the specific choices available in this group.</p>
            </div>
            <button 
              @click="addOption"
              type="button"
              class="flex items-center text-sm font-medium text-blue-700 bg-blue-50 hover:bg-blue-100 px-3 py-1.5 rounded-lg transition-colors border border-blue-200"
            >
              <Plus class="w-4 h-4 mr-1" />
              Add Option
            </button>
          </div>
          
          <div class="p-0 overflow-x-auto flex-grow">
            <table class="w-full text-sm text-left text-gray-500">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50 border-b border-gray-200">
                <tr>
                  <th scope="col" class="w-10 px-4 py-3"></th>
                  <th scope="col" class="px-4 py-3 font-semibold">Option Name <span class="text-red-600">*</span></th>
                  <th scope="col" class="px-4 py-3 font-semibold w-40">Price Adj. (+Rp)</th>
                  <th scope="col" class="px-4 py-3 font-semibold w-32">Status</th>
                  <th scope="col" class="px-4 py-3 font-semibold w-16"></th>
                </tr>
              </thead>
              <tbody>
                <tr v-if="formData.options?.length === 0" class="border-b border-gray-100">
                  <td colspan="5" class="px-4 py-8 text-center text-gray-500">
                    No options added yet. Click "Add Option" to create one.
                  </td>
                </tr>
                <tr 
                  v-for="(option, index) in formData.options" 
                  :key="index"
                  class="border-b border-gray-100 hover:bg-gray-50 group"
                >
                  <td class="px-4 py-3 text-gray-400 cursor-move">
                    <GripVertical class="w-4 h-4" />
                  </td>
                  <td class="px-4 py-3">
                    <input 
                      type="text" 
                      v-model="option.name"
                      class="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2" 
                      placeholder="e.g. Less Sugar"
                      required
                    >
                  </td>
                  <td class="px-4 py-3">
                    <input 
                      type="number" 
                      v-model="option.priceAdjustment"
                      class="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2" 
                    >
                  </td>
                  <td class="px-4 py-3">
                    <select 
                      v-model="option.status"
                      class="bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2"
                    >
                      <option value="Active">Active</option>
                      <option value="Inactive">Inactive</option>
                    </select>
                  </td>
                  <td class="px-4 py-3 text-right">
                    <button 
                      @click="removeOption(index)"
                      type="button"
                      class="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                      title="Remove Option"
                    >
                      <Trash2 class="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          
        </div>
      </div>
      
    </div>
  </div>
</template>
